import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const pretandard = localFont({
  src: "./assets/fonts/Pretendard-Medium.woff",
});

export const metadata: Metadata = {
  title: "blap-log",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretandard.className} antialiased`}>{children}</body>
    </html>
  );
}
